name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version from Git
      id: vars
      run: |
        GIT_SHA_SHORT=$(git rev-parse --short HEAD)
        echo "GIT_SHA_SHORT=$GIT_SHA_SHORT" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aura-khushi:${{ env.GIT_SHA_SHORT }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/aura-khushi:${{ env.GIT_SHA_SHORT }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.22.0

    - name: Decode and configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 --decode > $HOME/.kube/config

    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/aura aura=${{ secrets.DOCKERHUB_USERNAME }}/aura-khushi:${{ env.GIT_SHA_SHORT }} -n auraadventurejunction-in
        kubectl rollout status deployment/aura -n auraadventurejunction-in
